[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AJ-9005", email = "sharmaaanj1@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.141.1",
    "motor>=3.7.1",
    "passlib[bcrypt]>=1.7.4",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.14.0",
    "pymongo>=4.18.1",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
